/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.polivoto.vistas;

import com.polivoto.logica.ConstruirDatos;
import com.polivoto.logica.Cronometro;
import com.polivoto.logica.RecibirVotos;
import com.polivoto.main.BackBone;
import com.polivoto.networking.IOHandler;
import java.awt.CardLayout;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author azaraf
 */
public class AnalistaD extends JFrame {
    private final BackBone padre;
    private String nombreStartUp;
    private CardLayout cardLayout = new CardLayout();
    boolean progreso = true;
    Cronometro cronometro;
    RecibirVotos escuchar;
    int votos = 0;
    Integer poblacion;
    /**
     * Creates new form AnalistaD
     */
    public AnalistaD(BackBone padre) {
        this.padre = padre;
        initComponents();
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        // Obtener el nombre de la zona
        nombreStartUp = ConstruirDatos.getNombreStartUp();
        encabezado.setText("<html><div align=\"center\"" + nombreStartUp + "</html>");
        panelProceso.setLayout(cardLayout);
        panelProceso.add(pnl_esperar, "esperar");
        panelProceso.add(pnl_prog, "proceso");
        panelProceso.add(pnl_consultar, "consultar");
        cardLayout.show(panelProceso, "proceso");
        
    }

    public void beginListening() {
        Service service = new Service();
        service.start();
    }
    
    private class Service extends Thread{
        private IOHandler ioh;
        @Override
        public void run() {
            try {
                ServerSocket server = new ServerSocket(5004);
                JSONObject json;
                json = new JSONObject(ConstruirDatos.getAccionesConsultor().consultaParametrosIniciales());
                cronometro = new Cronometro(lblhrs, lblmin, lblseg, json.getInt("horas"), json.getInt("minutos"), json.getInt("segundos"), cardLayout, panelProceso);
                cronometro.iniciarCronometro();
                escuchar = new RecibirVotos();
                poblacion = json.getInt("poblacion");
                System.out.println("Startup dada: " + json.toString());
                escuchar.iniciarEscucha(votos - 1, poblacion, lblvotos_totales, lblporcentaje, pnlgrafica, pnl_consultar, pnl_esperar);

                /*
                 * Inicia cronómetro
                 */
                while (RecibirVotos.RECIBIENDO) {
                    Socket socket = server.accept(); // We should perform some kind of validation...
                    ioh = new IOHandler(new DataInputStream(socket.getInputStream()), new DataOutputStream(socket.getOutputStream()));
                    json = new JSONObject(new String(ioh.handleIncommingMessage()));
                    ioh.close();
                    socket.close();
                    switch (json.getInt("action")) {
                        case 1:
                            System.out.println("Voto nuevo");
                            escuchar.actualizarConteo();
                            break;
                        case 2:
                            System.out.println("Proceso Finalizado");
                            escuchar.pnl_consulta.setVisible(true);
                            escuchar.pnl_espera.setVisible(false);
                            RecibirVotos.RECIBIENDO = false;
                            break;
                        case 3:
                            poblacion = json.getInt("poblacion");
                            escuchar.votos--;
                            escuchar.actualizarConteo();
                            break;
                    }
                    socket.close();
                }
            } catch (JSONException | IOException e) {
                e.printStackTrace();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_consultar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_esperar = new javax.swing.JPanel();
        lblmsj_esperando = new javax.swing.JLabel();
        lbl_cargando = new javax.swing.JLabel();
        pnl_prog = new javax.swing.JPanel();
        lblmsj_esperando1 = new javax.swing.JLabel();
        lbl_cargando1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelVotosTotales = new javax.swing.JPanel();
        lbl_votos_totales = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblvotos_totales = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnl_vota_prog = new javax.swing.JPanel();
        panelProceso = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelEstado = new javax.swing.JPanel();
        encabezado = new javax.swing.JLabel();
        panelPorcentaje = new javax.swing.JPanel();
        lbl_porcentaje = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblporcentaje = new javax.swing.JLabel();
        pnlgrafica = new javax.swing.JPanel();
        panelTimer = new javax.swing.JPanel();
        lbl_tiemporest = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblhrs = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblmin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblseg = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblpuntos = new javax.swing.JLabel();
        lblpuntos1 = new javax.swing.JLabel();

        pnl_consultar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AHORA PUEDES CONSULTAR LOS RESULTADOS FINALES.");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polivoto/imagenes/boton-consultar1.png"))); // NOI18N

        javax.swing.GroupLayout pnl_consultarLayout = new javax.swing.GroupLayout(pnl_consultar);
        pnl_consultar.setLayout(pnl_consultarLayout);
        pnl_consultarLayout.setHorizontalGroup(
            pnl_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_consultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_consultarLayout.setVerticalGroup(
            pnl_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_consultarLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnl_esperar.setBackground(new java.awt.Color(255, 255, 255));

        lblmsj_esperando.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblmsj_esperando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmsj_esperando.setText("<html><div align=\"center\">VOTACION EN CURSO</html>");

        lbl_cargando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polivoto/imagenes/participando.gif"))); // NOI18N

        javax.swing.GroupLayout pnl_esperarLayout = new javax.swing.GroupLayout(pnl_esperar);
        pnl_esperar.setLayout(pnl_esperarLayout);
        pnl_esperarLayout.setHorizontalGroup(
            pnl_esperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmsj_esperando)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_esperarLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(lbl_cargando)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnl_esperarLayout.setVerticalGroup(
            pnl_esperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_esperarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblmsj_esperando, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_cargando)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_prog.setBackground(new java.awt.Color(255, 255, 255));

        lblmsj_esperando1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblmsj_esperando1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmsj_esperando1.setText("<html><div align=\"center\">ESPERANDO A LOS ÚLTIMOS USUARIOS QUE YA HABÍAN INICIADO SU PROCESO DE VOTACIÓN FINALICEN.</html>");

        lbl_cargando1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polivoto/imagenes/espera.gif"))); // NOI18N

        javax.swing.GroupLayout pnl_progLayout = new javax.swing.GroupLayout(pnl_prog);
        pnl_prog.setLayout(pnl_progLayout);
        pnl_progLayout.setHorizontalGroup(
            pnl_progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmsj_esperando1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_progLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_cargando1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_progLayout.setVerticalGroup(
            pnl_progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_progLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblmsj_esperando1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_cargando1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(134, 36, 31));
        jPanel1.setPreferredSize(new java.awt.Dimension(846, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polivoto/imagenes/logo-pequeno.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelVotosTotales.setBackground(new java.awt.Color(255, 255, 255));
        panelVotosTotales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 3, true));

        lbl_votos_totales.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_votos_totales.setText("VOTOS TOTALES:");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lblvotos_totales.setFont(new java.awt.Font("Roboto", 1, 100)); // NOI18N
        lblvotos_totales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblvotos_totales.setText("0");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 40)); // NOI18N
        jLabel6.setText("VOTOS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblvotos_totales, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblvotos_totales, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelVotosTotalesLayout = new javax.swing.GroupLayout(panelVotosTotales);
        panelVotosTotales.setLayout(panelVotosTotalesLayout);
        panelVotosTotalesLayout.setHorizontalGroup(
            panelVotosTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVotosTotalesLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panelVotosTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelVotosTotalesLayout.createSequentialGroup()
                        .addComponent(lbl_votos_totales)
                        .addGap(0, 373, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelVotosTotalesLayout.setVerticalGroup(
            panelVotosTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVotosTotalesLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbl_votos_totales)
                .addGap(8, 8, 8)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelPrincipal.add(panelVotosTotales, gridBagConstraints);

        pnl_vota_prog.setBackground(new java.awt.Color(255, 255, 255));
        pnl_vota_prog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 3, true));

        panelProceso.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelProcesoLayout = new javax.swing.GroupLayout(panelProceso);
        panelProceso.setLayout(panelProcesoLayout);
        panelProcesoLayout.setHorizontalGroup(
            panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        panelProcesoLayout.setVerticalGroup(
            panelProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("INFORMACIÓN:");

        panelEstado.setBackground(new java.awt.Color(255, 255, 255));

        encabezado.setBackground(new java.awt.Color(255, 255, 255));
        encabezado.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        encabezado.setForeground(new java.awt.Color(102, 0, 0));
        encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezado.setText("VOTACIONES EN PROGRESO");

        javax.swing.GroupLayout panelEstadoLayout = new javax.swing.GroupLayout(panelEstado);
        panelEstado.setLayout(panelEstadoLayout);
        panelEstadoLayout.setHorizontalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEstadoLayout.setVerticalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout pnl_vota_progLayout = new javax.swing.GroupLayout(pnl_vota_prog);
        pnl_vota_prog.setLayout(pnl_vota_progLayout);
        pnl_vota_progLayout.setHorizontalGroup(
            pnl_vota_progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_vota_progLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(panelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(pnl_vota_progLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_vota_progLayout.createSequentialGroup()
                .addComponent(panelProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_vota_progLayout.setVerticalGroup(
            pnl_vota_progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_vota_progLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(panelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(panelProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelPrincipal.add(pnl_vota_prog, gridBagConstraints);

        panelPorcentaje.setBackground(new java.awt.Color(255, 255, 255));
        panelPorcentaje.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 3, true));

        lbl_porcentaje.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lbl_porcentaje.setText("PORCENTAJE DE PARTICIPACIÓN:");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblporcentaje.setBackground(new java.awt.Color(255, 255, 255));
        lblporcentaje.setFont(new java.awt.Font("Roboto", 1, 80)); // NOI18N
        lblporcentaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblporcentaje.setText("0%");

        pnlgrafica.setEnabled(false);

        javax.swing.GroupLayout pnlgraficaLayout = new javax.swing.GroupLayout(pnlgrafica);
        pnlgrafica.setLayout(pnlgraficaLayout);
        pnlgraficaLayout.setHorizontalGroup(
            pnlgraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlgraficaLayout.setVerticalGroup(
            pnlgraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblporcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlgrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlgrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPorcentajeLayout = new javax.swing.GroupLayout(panelPorcentaje);
        panelPorcentaje.setLayout(panelPorcentajeLayout);
        panelPorcentajeLayout.setHorizontalGroup(
            panelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPorcentajeLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPorcentajeLayout.createSequentialGroup()
                        .addComponent(lbl_porcentaje)
                        .addGap(0, 188, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPorcentajeLayout.setVerticalGroup(
            panelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPorcentajeLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbl_porcentaje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPorcentajeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelPrincipal.add(panelPorcentaje, gridBagConstraints);

        panelTimer.setBackground(new java.awt.Color(255, 255, 255));
        panelTimer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 3, true));

        lbl_tiemporest.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_tiemporest.setText("TIEMPO RESTANTE:");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhrs.setBackground(new java.awt.Color(255, 255, 255));
        lblhrs.setFont(new java.awt.Font("Roboto", 1, 90)); // NOI18N
        lblhrs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblhrs.setText("00");
        lblhrs.setOpaque(true);
        jPanel9.add(lblhrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 140, 80));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hrs");
        jLabel7.setOpaque(true);
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 40));

        lblmin.setBackground(new java.awt.Color(255, 255, 255));
        lblmin.setFont(new java.awt.Font("Roboto", 1, 90)); // NOI18N
        lblmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmin.setText("00");
        lblmin.setOpaque(true);
        jPanel9.add(lblmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 130, 80));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("seg");
        jLabel9.setOpaque(true);
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 100, 60));

        lblseg.setBackground(new java.awt.Color(255, 255, 255));
        lblseg.setFont(new java.awt.Font("Roboto", 1, 90)); // NOI18N
        lblseg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblseg.setText("00");
        lblseg.setOpaque(true);
        jPanel9.add(lblseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 120, 80));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("min");
        jLabel11.setOpaque(true);
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 100, 40));

        lblpuntos.setBackground(new java.awt.Color(255, 255, 255));
        lblpuntos.setFont(new java.awt.Font("Roboto", 1, 90)); // NOI18N
        lblpuntos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpuntos.setText(":");
        lblpuntos.setOpaque(true);
        jPanel9.add(lblpuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 40, 70));

        lblpuntos1.setBackground(new java.awt.Color(255, 255, 255));
        lblpuntos1.setFont(new java.awt.Font("Roboto", 1, 90)); // NOI18N
        lblpuntos1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpuntos1.setText(":");
        lblpuntos1.setOpaque(true);
        jPanel9.add(lblpuntos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 40, 70));

        javax.swing.GroupLayout panelTimerLayout = new javax.swing.GroupLayout(panelTimer);
        panelTimer.setLayout(panelTimerLayout);
        panelTimerLayout.setHorizontalGroup(
            panelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimerLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTimerLayout.createSequentialGroup()
                        .addComponent(lbl_tiemporest)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTimerLayout.setVerticalGroup(
            panelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimerLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbl_tiemporest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTimerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelPrincipal.add(panelTimer, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalistaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalistaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalistaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalistaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel encabezado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_cargando;
    private javax.swing.JLabel lbl_cargando1;
    private javax.swing.JLabel lbl_porcentaje;
    private javax.swing.JLabel lbl_tiemporest;
    private javax.swing.JLabel lbl_votos_totales;
    private javax.swing.JLabel lblhrs;
    private javax.swing.JLabel lblmin;
    private javax.swing.JLabel lblmsj_esperando;
    private javax.swing.JLabel lblmsj_esperando1;
    private javax.swing.JLabel lblporcentaje;
    private javax.swing.JLabel lblpuntos;
    private javax.swing.JLabel lblpuntos1;
    private javax.swing.JLabel lblseg;
    private javax.swing.JLabel lblvotos_totales;
    private javax.swing.JPanel panelEstado;
    private javax.swing.JPanel panelPorcentaje;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelProceso;
    private javax.swing.JPanel panelTimer;
    private javax.swing.JPanel panelVotosTotales;
    private javax.swing.JPanel pnl_consultar;
    private javax.swing.JPanel pnl_esperar;
    private javax.swing.JPanel pnl_prog;
    private javax.swing.JPanel pnl_vota_prog;
    private javax.swing.JPanel pnlgrafica;
    // End of variables declaration//GEN-END:variables
}
